--
-- PostgreSQL database dump
--

\restrict UaHySknud9bVhBiH9CLC9vPtPEQ5BW2CmYYicPC2ikQvhIJndnddh0VOje0jK4a

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: r13b_mod_service_interaction; Type: SCHEMA; Schema: -; Owner: folio_admin
--

CREATE SCHEMA r13b_mod_service_interaction;


ALTER SCHEMA r13b_mod_service_interaction OWNER TO folio_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_setting; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.app_setting (
    st_id character varying(36) NOT NULL,
    st_version bigint NOT NULL,
    st_section character varying(255),
    st_key character varying(255),
    st_setting_type character varying(255),
    st_vocab character varying(255),
    st_default_value character varying(255),
    st_value text,
    st_hidden boolean
);


ALTER TABLE r13b_mod_service_interaction.app_setting OWNER TO folio_admin;

--
-- Name: custom_property; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property (
    id bigint NOT NULL,
    version bigint NOT NULL,
    definition_id character varying(36),
    parent_id bigint,
    note text,
    internal boolean NOT NULL,
    public_note text
);


ALTER TABLE r13b_mod_service_interaction.custom_property OWNER TO folio_admin;

--
-- Name: custom_property_blob; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_blob (
    id bigint NOT NULL,
    value oid NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_blob OWNER TO folio_admin;

--
-- Name: custom_property_boolean; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_boolean (
    id bigint NOT NULL,
    value boolean NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_boolean OWNER TO folio_admin;

--
-- Name: custom_property_container; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_container (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_container OWNER TO folio_admin;

--
-- Name: custom_property_decimal; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_decimal (
    id bigint NOT NULL,
    value numeric(19,2) NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_decimal OWNER TO folio_admin;

--
-- Name: custom_property_definition; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_definition (
    pd_id character varying(36) NOT NULL,
    version bigint NOT NULL,
    pd_name character varying(255) NOT NULL,
    pd_type character varying(255) NOT NULL,
    pd_description text,
    pd_label character varying(255) NOT NULL,
    pd_weight integer NOT NULL,
    pd_primary boolean NOT NULL,
    default_internal boolean NOT NULL,
    pd_ctx character varying(255),
    pd_retired boolean NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_definition OWNER TO folio_admin;

--
-- Name: custom_property_id_seq; Type: SEQUENCE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE r13b_mod_service_interaction.custom_property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME r13b_mod_service_interaction.custom_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_property_integer; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_integer (
    id bigint NOT NULL,
    value bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_integer OWNER TO folio_admin;

--
-- Name: custom_property_multi_blob; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_blob (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_blob OWNER TO folio_admin;

--
-- Name: custom_property_multi_blob_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_blob_value (
    custom_property_multi_blob_id bigint CONSTRAINT custom_property_multi_blob__custom_property_multi_blob_not_null NOT NULL,
    "value_byte;" bytea
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_blob_value OWNER TO folio_admin;

--
-- Name: custom_property_multi_decimal; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_decimal (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_decimal OWNER TO folio_admin;

--
-- Name: custom_property_multi_decimal_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_decimal_value (
    custom_property_multi_decimal_id bigint CONSTRAINT custom_property_multi_decim_custom_property_multi_deci_not_null NOT NULL,
    value_big_decimal numeric(19,2)
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_decimal_value OWNER TO folio_admin;

--
-- Name: custom_property_multi_integer; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_integer (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_integer OWNER TO folio_admin;

--
-- Name: custom_property_multi_integer_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_integer_value (
    custom_property_multi_integer_id bigint CONSTRAINT custom_property_multi_integ_custom_property_multi_inte_not_null NOT NULL,
    value_big_integer numeric(19,2)
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_integer_value OWNER TO folio_admin;

--
-- Name: custom_property_multi_local_date; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_local_date (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_local_date OWNER TO folio_admin;

--
-- Name: custom_property_multi_local_date_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_local_date_value (
    custom_property_multi_local_date_id bigint CONSTRAINT custom_property_multi_local_custom_property_multi_loca_not_null NOT NULL,
    value_local_date date
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_local_date_value OWNER TO folio_admin;

--
-- Name: custom_property_multi_refdata; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_refdata (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_refdata OWNER TO folio_admin;

--
-- Name: custom_property_multi_refdata_refdata_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_refdata_refdata_value (
    custom_property_multi_refdata_value_id bigint CONSTRAINT custom_property_multi_refda_custom_property_multi_refd_not_null NOT NULL,
    refdata_value_id character varying(36)
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_refdata_refdata_value OWNER TO folio_admin;

--
-- Name: custom_property_multi_text; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_text (
    id bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_text OWNER TO folio_admin;

--
-- Name: custom_property_multi_text_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_multi_text_value (
    custom_property_multi_text_id bigint CONSTRAINT custom_property_multi_text__custom_property_multi_text_not_null NOT NULL,
    value_string character varying(255)
);


ALTER TABLE r13b_mod_service_interaction.custom_property_multi_text_value OWNER TO folio_admin;

--
-- Name: custom_property_refdata; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_refdata (
    id bigint NOT NULL,
    value_id character varying(36) NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_refdata OWNER TO folio_admin;

--
-- Name: custom_property_refdata_definition; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_refdata_definition (
    pd_id character varying(255) NOT NULL,
    category_id character varying(36) NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_refdata_definition OWNER TO folio_admin;

--
-- Name: custom_property_text; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.custom_property_text (
    id bigint NOT NULL,
    value text NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.custom_property_text OWNER TO folio_admin;

--
-- Name: dashboard; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.dashboard (
    dshb_id character varying(36) NOT NULL,
    dshb_version bigint NOT NULL,
    dshb_name character varying(255),
    dshb_description text
);


ALTER TABLE r13b_mod_service_interaction.dashboard OWNER TO folio_admin;

--
-- Name: dashboard_access; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.dashboard_access (
    da_id character varying(36) NOT NULL,
    da_version bigint NOT NULL,
    da_dashboard_fk character varying(36),
    da_user_fk character varying(36),
    da_access_fk character varying(36),
    da_date_created timestamp without time zone,
    da_user_dashboard_weight bigint,
    da_default_user_dashboard boolean NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.dashboard_access OWNER TO folio_admin;

--
-- Name: dashboard_display_data; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.dashboard_display_data (
    ddd_id character varying(36) NOT NULL,
    ddd_version bigint NOT NULL,
    ddd_dash_id character varying(36),
    ddd_layout_data text
);


ALTER TABLE r13b_mod_service_interaction.dashboard_display_data OWNER TO folio_admin;

--
-- Name: db_key_pair; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.db_key_pair (
    kp_id character varying(36) NOT NULL,
    kp_version bigint NOT NULL,
    kp_available_from timestamp without time zone,
    kp_expires_at timestamp without time zone,
    kp_usage character varying(32),
    kp_alg character varying(32),
    kp_public_key text,
    kp_private_key text
);


ALTER TABLE r13b_mod_service_interaction.db_key_pair OWNER TO folio_admin;

--
-- Name: external_user; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.external_user (
    eu_id character varying(36) NOT NULL,
    eu_version bigint NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.external_user OWNER TO folio_admin;

--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE SEQUENCE r13b_mod_service_interaction.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE r13b_mod_service_interaction.hibernate_sequence OWNER TO folio_admin;

--
-- Name: number_generator; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.number_generator (
    ng_id character varying(36) NOT NULL,
    ng_version bigint NOT NULL,
    ng_code character varying(36) NOT NULL,
    ng_name character varying(100) NOT NULL,
    ng_default_seq_code character varying(36),
    ng_description character varying(256)
);


ALTER TABLE r13b_mod_service_interaction.number_generator OWNER TO folio_admin;

--
-- Name: number_generator_sequence; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.number_generator_sequence (
    ngs_id character varying(36) NOT NULL,
    ngs_version bigint NOT NULL,
    ngs_owner character varying(36) NOT NULL,
    ngs_code character varying(36) NOT NULL,
    ngs_prefix character varying(100),
    ngs_postfix character varying(100),
    ngs_next_value bigint,
    ngs_format character varying(20),
    ngs_check_digit_algorithm_fk character varying(36),
    ngs_output_template character varying(256),
    ngs_description character varying(256),
    ngs_enabled boolean,
    ngs_name character varying(100),
    ngs_pre_checksum_template character varying(256),
    ngs_maximum_number bigint,
    ngs_maximum_number_threshold bigint,
    ngs_maximum_check_fk character varying(36),
    ngs_reset_on_year_change boolean DEFAULT false,
    ngs_last_used_year character varying(4)
);


ALTER TABLE r13b_mod_service_interaction.number_generator_sequence OWNER TO folio_admin;

--
-- Name: refdata_category; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.refdata_category (
    rdc_id character varying(36) NOT NULL,
    rdc_version bigint NOT NULL,
    rdc_description character varying(255) NOT NULL,
    internal boolean NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.refdata_category OWNER TO folio_admin;

--
-- Name: refdata_value; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.refdata_value (
    rdv_id character varying(36) NOT NULL,
    rdv_version bigint NOT NULL,
    rdv_value character varying(255) NOT NULL,
    rdv_owner character varying(36) NOT NULL,
    rdv_label character varying(255) NOT NULL
);


ALTER TABLE r13b_mod_service_interaction.refdata_value OWNER TO folio_admin;

--
-- Name: tenant_changelog; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.tenant_changelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE r13b_mod_service_interaction.tenant_changelog OWNER TO folio_admin;

--
-- Name: tenant_changelog_lock; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.tenant_changelog_lock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE r13b_mod_service_interaction.tenant_changelog_lock OWNER TO folio_admin;

--
-- Name: widget_definition; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.widget_definition (
    wdef_id character varying(36) NOT NULL,
    wdef_version bigint NOT NULL,
    wdef_definition_version character varying(36),
    wdef_name character varying(255),
    wdef_definition text,
    wdef_type_name character varying(255),
    wdef_type_version character varying(36)
);


ALTER TABLE r13b_mod_service_interaction.widget_definition OWNER TO folio_admin;

--
-- Name: widget_instance; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.widget_instance (
    wins_id character varying(36) NOT NULL,
    wins_version bigint NOT NULL,
    wins_name character varying(255),
    wins_definition_name character varying(255),
    wins_definition_version character varying(36),
    wins_owner_fk character varying(36),
    wins_configuration text,
    wins_weight bigint
);


ALTER TABLE r13b_mod_service_interaction.widget_instance OWNER TO folio_admin;

--
-- Name: widget_type; Type: TABLE; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE TABLE r13b_mod_service_interaction.widget_type (
    wtype_id character varying(36) NOT NULL,
    wtype_version bigint NOT NULL,
    wtype_type_version character varying(36),
    wtype_name character varying(255),
    wtype_schema text
);


ALTER TABLE r13b_mod_service_interaction.widget_type OWNER TO folio_admin;

--
-- Data for Name: app_setting; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.app_setting (st_id, st_version, st_section, st_key, st_setting_type, st_vocab, st_default_value, st_value, st_hidden) FROM stdin;
ff8081819f838b7f019f838ea0490023	0	test	test_app_setting	String	\N	\N	\N	\N
ff8081819f838b7f019f838eb5990025	0	m4	alpha	String	\N	\N	one	\N
ff8081819f838b7f019f838eb5aa0026	0	m4	secret	Password	\N	\N	s3cr3t	t
\.


--
-- Data for Name: custom_property; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property (id, version, definition_id, parent_id, note, internal, public_note) FROM stdin;
\.


--
-- Data for Name: custom_property_blob; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_blob (id, value) FROM stdin;
\.


--
-- Data for Name: custom_property_boolean; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_boolean (id, value) FROM stdin;
\.


--
-- Data for Name: custom_property_container; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_container (id) FROM stdin;
\.


--
-- Data for Name: custom_property_decimal; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_decimal (id, value) FROM stdin;
\.


--
-- Data for Name: custom_property_definition; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_definition (pd_id, version, pd_name, pd_type, pd_description, pd_label, pd_weight, pd_primary, default_internal, pd_ctx, pd_retired) FROM stdin;
ff8081819f838b7f019f838ea04e0024	0	test	com.k_int.web.toolkit.custprops.types.CustomPropertyText	\N	test	0	f	f	\N	f
\.


--
-- Data for Name: custom_property_integer; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_integer (id, value) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_blob; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_blob (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_blob_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_blob_value (custom_property_multi_blob_id, "value_byte;") FROM stdin;
\.


--
-- Data for Name: custom_property_multi_decimal; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_decimal (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_decimal_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_decimal_value (custom_property_multi_decimal_id, value_big_decimal) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_integer; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_integer (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_integer_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_integer_value (custom_property_multi_integer_id, value_big_integer) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_local_date; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_local_date (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_local_date_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_local_date_value (custom_property_multi_local_date_id, value_local_date) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_refdata; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_refdata (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_refdata_refdata_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_refdata_refdata_value (custom_property_multi_refdata_value_id, refdata_value_id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_text; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_text (id) FROM stdin;
\.


--
-- Data for Name: custom_property_multi_text_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_multi_text_value (custom_property_multi_text_id, value_string) FROM stdin;
\.


--
-- Data for Name: custom_property_refdata; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_refdata (id, value_id) FROM stdin;
\.


--
-- Data for Name: custom_property_refdata_definition; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_refdata_definition (pd_id, category_id) FROM stdin;
\.


--
-- Data for Name: custom_property_text; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.custom_property_text (id, value) FROM stdin;
\.


--
-- Data for Name: dashboard; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.dashboard (dshb_id, dshb_version, dshb_name, dshb_description) FROM stdin;
74e8c61c-9751-4420-a136-7411a1545003	0	My dashboard	\N
cc20473e-caf4-424f-982a-6a490f427f22	0	My dashboard	\N
38668b57-5a37-44f8-adec-5594f02067a0	0	Migration Board	\N
\.


--
-- Data for Name: dashboard_access; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.dashboard_access (da_id, da_version, da_dashboard_fk, da_user_fk, da_access_fk, da_date_created, da_user_dashboard_weight, da_default_user_dashboard) FROM stdin;
6dd8d4f8-f645-4e43-a1a1-a141bc7e4ae4	0	74e8c61c-9751-4420-a136-7411a1545003	11111111-1111-1111-1111-111111111111	120eb666edcb10909a9dfc5a4565b172	2026-07-21 07:23:15.141	0	t
6c6eadb9-cd41-4335-8dfb-12633559ebfa	0	cc20473e-caf4-424f-982a-6a490f427f22	22222222-2222-2222-2222-222222222222	120eb666edcb10909a9dfc5a4565b172	2026-07-21 07:23:15.18	0	t
1f678189-3f76-429d-a732-413d1e9ce702	0	38668b57-5a37-44f8-adec-5594f02067a0	11111111-1111-1111-1111-111111111111	120eb666edcb10909a9dfc5a4565b172	2026-07-21 07:23:15.212	1	f
0fb40258-2717-4616-8d99-9d4e3b68a4ba	0	38668b57-5a37-44f8-adec-5594f02067a0	22222222-2222-2222-2222-222222222222	ff8081819f838b7f019f838e9f71001a	2026-07-21 07:23:15.245	1	f
\.


--
-- Data for Name: dashboard_display_data; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.dashboard_display_data (ddd_id, ddd_version, ddd_dash_id, ddd_layout_data) FROM stdin;
3d4fc095-e1b9-429f-bf48-de1784b9147f	0	74e8c61c-9751-4420-a136-7411a1545003	\N
253a75b6-b2c8-439a-8505-12a3f9933d8c	0	cc20473e-caf4-424f-982a-6a490f427f22	\N
1fe94fdb-3e5a-47dd-912b-e1d0ebe226de	0	38668b57-5a37-44f8-adec-5594f02067a0	\N
\.


--
-- Data for Name: db_key_pair; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.db_key_pair (kp_id, kp_version, kp_available_from, kp_expires_at, kp_usage, kp_alg, kp_public_key, kp_private_key) FROM stdin;
0037095c-8fbf-44fd-bc4a-96039e298f3a	0	2026-07-21 07:25:01.747516	2028-07-20 07:25:01.747516	extApp	RSA	MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoh/SnN+fhnG9O7S3nRX1xMQp0GSi7WpfLMpk+/OSScP9bBb313RI/fxykKdVm3VR/JT3rZz3tmpku63LgAi1vq8jshhC4lbJN3lDOz5rMCHTmnweLt7myGCHcId6EWLOSiT/lQPXWlp1xmhTtDJDAuuf4VlTrwDuu9pRTlL+AzqPIi64HvgbJDgEWRD0D9lg+wmBYvO1Li+XDdXIeiTFIs1bqvN4nZRcgA4goRfE1dLenYyUoEmUqrraYn8M1tCYcKCxzO5Ew8QAid+dKZhVCv6DIJo2Ui+axX5bVc9UL+sDsTbKYf/K/HkHNFUxqckswVu19dIbCsQwAr+hwDt9PQIDAQAB	MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiH9Kc35+Gcb07tLedFfXExCnQZKLtal8symT785JJw/1sFvfXdEj9/HKQp1WbdVH8lPetnPe2amS7rcuACLW+ryOyGELiVsk3eUM7PmswIdOafB4u3ubIYIdwh3oRYs5KJP+VA9daWnXGaFO0MkMC65/hWVOvAO672lFOUv4DOo8iLrge+BskOARZEPQP2WD7CYFi87UuL5cN1ch6JMUizVuq83idlFyADiChF8TV0t6djJSgSZSqutpifwzW0JhwoLHM7kTDxACJ350pmFUK/oMgmjZSL5rFfltVz1Qv6wOxNsph/8r8eQc0VTGpySzBW7X10hsKxDACv6HAO309AgMBAAECggEACz/8DxNcGtSKVg9Ml85DTKZ0DwLnZLl3O0DG0HjuvhxR2eNKIB2bRwydLTkqBpdAhi9sHxRVAsfP5PoYCfK7cdeYuYNXeM9JjTDmn8DNZ/yg610Q1x3JPpRRhwHPpaSJPg8327D1i6Pap6xA9VsbgqNeZ8vECSZzv9NUGwRFSMH2GbWVAAW6bvKFD2zTdPRC9lBsxR+I2lwmSMGhOaIyEFZ2uAGuQsKpbqPc66W0lTph3hSZqO/XSFuIK6BGHKIPQjkiXZvoHTA8LCUq+AWsz72gP9Gb8BKih6dmbua+5GoxYSc0Lhk849JSMXtFQEJVTovyNFyDpCrb3MyLuPJFfQKBgQC5BMT6ytDpR1aGQZa0dZN7FYzAkbdQWni1NO47epT2XexXVdLjT+cG5zqxCNm0ohM/JOyxST1voH1vEaBzrLOtFGPLlsjO+fbUD8mKvJVLBABrldYt4qXGCnVD4Zfqp85uLvuVihPndwFlj6NepD+f1LkVu+eRloGV9qFrsqjDKwKBgQDgUoiasYoACxmFo1ViKO8xgKU92ZGfSI8VqRkgeFeNBtyaqeGm3FOv2sP2H8KBv4GaFB2t2b/bGQ4o9O/9G54KvKUeuZfOVMl5w5XP7v4mrPS/ebLDy56gFK0RK3Ujqd0Y+FGvmcA5oH6hL3LURI1YtdkrLTW5lV6dcbQDkYEtNwKBgGBciI8qFLZ6ziisfmZMmlxPs/gTrIrwI9AU2kMmK/FIp7Aw5d44HlYtFhdgSarXgvivLYuEXrgFuW6gmpXEi+wII5XEWZ/a9mAqPMjCQWtJkUJ3To6lbbuAdOS+2RWBAnXGiIew238BLzwLHIZNO0nuS9ty+z+LSMCnLBlgep7zAoGBALZcok0QE94hJ+hqdhlMqdeWe78iRq408I1tYM3yx0oQz/q0LIvYBfiqYjCOdTPBmfzGabJRmRTm84n8RbWAZCTaY2ns+ypz5y6kAACAjACpDncy2k8uE5CT/nY83AfYKbQI+29EEO9IOGmVB0blS/tYKmpdYJW0hqx8KRnViixVAoGAWKtC/cBgOp9WETZJk0NcuKJ7iDx09mHenUkzHPAMbvB/P0KYB+azNrhKRoFDjyhcwlUN04qql2UkTSwHNeGdoct057g9BnmLKEMbTxRoJ8IcjehCfc9Z2zgp+xyo3GJvpPtXnKrdqH+A6RYyxvuUZmH14LKTqsEaZJT1AqVh4XI=
\.


--
-- Data for Name: external_user; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.external_user (eu_id, eu_version) FROM stdin;
11111111-1111-1111-1111-111111111111	0
22222222-2222-2222-2222-222222222222	0
\.


--
-- Data for Name: number_generator; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.number_generator (ng_id, ng_version, ng_code, ng_name, ng_default_seq_code, ng_description) FROM stdin;
103c1e27-6894-4d54-9f46-002382494a36	0	openAccess	Open access: Publication request number	\N	\N
f37ab61d-f339-4e03-aeb3-35cdcae9ac4e	0	patronRequest	ILL: Patron request number	\N	\N
35464c82-c61e-4a12-8b1a-bb7bbf1ac18e	0	users_patronBarcode	Users: Patron barcode	\N	\N
8cce42f9-5f71-4a07-8f76-922bce2c977f	0	organizations_vendorCode	Organizations: Vendor code	\N	\N
59aae062-bba9-4273-b8af-5871f19c2ec6	0	inventory_accessionNumber	Inventory: Accession number	\N	\N
9cf07b16-b56a-4727-b084-b59099a7e0dd	0	inventory_callNumber	Inventory: Call number	\N	\N
25aefdab-ed5f-47f8-b93c-c6e95bcb0780	0	inventory_itemBarcode	Inventory: Item barcode	\N	\N
f86166e4-6220-419f-960f-9733554d7f54	0	serialsManagement_patternNumber	Serials management: Pattern number	\N	\N
bbf6cda4-e0dc-4fc7-b969-6081f0d198f1	0	m4gen	M4 Generator	\N	\N
\.


--
-- Data for Name: number_generator_sequence; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.number_generator_sequence (ngs_id, ngs_version, ngs_owner, ngs_code, ngs_prefix, ngs_postfix, ngs_next_value, ngs_format, ngs_check_digit_algorithm_fk, ngs_output_template, ngs_description, ngs_enabled, ngs_name, ngs_pre_checksum_template, ngs_maximum_number, ngs_maximum_number_threshold, ngs_maximum_check_fk, ngs_reset_on_year_change, ngs_last_used_year) FROM stdin;
2bb420aa-4e7b-4998-ac62-9bff3356fd9a	0	103c1e27-6894-4d54-9f46-002382494a36	requestSequence	\N	\N	1	000000000	ff8081819f838b7f019f838e9f7a001c	oa-${generated_number}	\N	t	Request sequence	\N	\N	\N	\N	f	\N
a0bb1ca9-59e2-4f8b-91a0-b20d88027776	0	f37ab61d-f339-4e03-aeb3-35cdcae9ac4e	requestSequence	\N	\N	1	000000000	ff8081819f838b7f019f838e9f7d001d	ill-${generated_number}-${checksum}	\N	t	Request sequence	\N	\N	\N	\N	f	\N
c7bb2ce7-3c84-489a-8d2e-29029dfd722a	0	35464c82-c61e-4a12-8b1a-bb7bbf1ac18e	patron	\N	\N	1	000000000	ff8081819f838b7f019f838e9f7d001d	P${generated_number}-${checksum}	\N	t	Patron	\N	\N	\N	\N	f	\N
38e7da59-f037-4f5b-9d7b-fadd59f00564	0	35464c82-c61e-4a12-8b1a-bb7bbf1ac18e	staff	\N	\N	1	000000000	ff8081819f838b7f019f838e9f7d001d	S${generated_number}-${checksum}	\N	t	Staff	\N	\N	\N	\N	f	\N
00188aac-a112-424c-ad7e-f41cc8d33d6f	0	8cce42f9-5f71-4a07-8f76-922bce2c977f	vendor	\N	\N	1	000	ff8081819f838b7f019f838e9f7a001c	K${generated_number}	\N	t	Vendor	\N	\N	\N	\N	f	\N
c7cfcb5e-e7b4-423e-a707-191efb18f2c9	0	9cf07b16-b56a-4727-b084-b59099a7e0dd	callNumber	\N	\N	1	00000	ff8081819f838b7f019f838e9f7a001c	B 2023 / ${generated_number}	\N	t	Call number	\N	\N	\N	\N	f	\N
41e75e47-d049-4c2a-856c-77b483e98b44	0	25aefdab-ed5f-47f8-b93c-c6e95bcb0780	itemBarcode	\N	\N	1	0000000000	ff8081819f838b7f019f838e9f7a001c	${generated_number}	\N	t	Item barcode	\N	\N	\N	\N	f	\N
d6afbc31-3499-4e3a-aa37-4a3dca7576f9	0	f86166e4-6220-419f-960f-9733554d7f54	patternNumber	\N	\N	1	000000000	ff8081819f838b7f019f838e9f7a001c	pattern-${generated_number}	\N	t	Pattern number	\N	\N	\N	\N	f	\N
b9acf273-b3c3-449c-b1b3-73b22cca7ff7	3	bbf6cda4-e0dc-4fc7-b969-6081f0d198f1	plain	m4-	\N	4	00000	\N	\N	\N	t	plain	\N	\N	\N	\N	f	2026
23ad1441-e353-41c4-9fb4-3ec93a14a0d6	1	bbf6cda4-e0dc-4fc7-b969-6081f0d198f1	checked	\N	\N	2	000000000	ff8081819f838b7f019f838e9f7d001d	0698${generated_number}${checksum}	\N	t	checked	\N	\N	\N	\N	f	2026
409c05e3-fa19-47ac-add9-b967729a4fcd	1	59aae062-bba9-4273-b8af-5871f19c2ec6	accessionNumber	\N	\N	2	00000	ff8081819f838b7f019f838e9f7a001c	31A-2023-${generated_number}	\N	t	Accession number	\N	\N	\N	\N	f	2026
\.


--
-- Data for Name: refdata_category; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.refdata_category (rdc_id, rdc_version, rdc_description, internal) FROM stdin;
eec19c003b9d198c043a0d3838f5b26a	0	DashboardAccess.Access	t
ff8081819f838b7f019f838e9f560015	0	NumberGeneratorSequence.MaximumCheck	t
ff8081819f838b7f019f838e9f78001b	0	NumberGeneratorSequence.CheckDigitAlgo	t
ff8081819f838b7f019f838eb5bb0027	0	M4.Custom	f
\.


--
-- Data for Name: refdata_value; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.refdata_value (rdv_id, rdv_version, rdv_value, rdv_owner, rdv_label) FROM stdin;
120eb666edcb10909a9dfc5a4565b172	0	manage	eec19c003b9d198c043a0d3838f5b26a	Manage
ff8081819f838b7f019f838e9f580016	0	below_threshold	ff8081819f838b7f019f838e9f560015	Below threshold
ff8081819f838b7f019f838e9f650017	0	over_threshold	ff8081819f838b7f019f838e9f560015	Over threshold
ff8081819f838b7f019f838e9f680018	0	at_maximum	ff8081819f838b7f019f838e9f560015	At maximum
ff8081819f838b7f019f838e9f6e0019	0	edit	eec19c003b9d198c043a0d3838f5b26a	Edit
ff8081819f838b7f019f838e9f71001a	0	view	eec19c003b9d198c043a0d3838f5b26a	View
ff8081819f838b7f019f838e9f7a001c	0	none	ff8081819f838b7f019f838e9f78001b	None
ff8081819f838b7f019f838e9f7d001d	0	ean13	ff8081819f838b7f019f838e9f78001b	31-RTL-mod10-I (EAN)
ff8081819f838b7f019f838e9f7f001e	0	1793_ltr_mod10_r	ff8081819f838b7f019f838e9f78001b	1793-LTR-mod10-R
ff8081819f838b7f019f838e9f81001f	0	12_ltr_mod10_r	ff8081819f838b7f019f838e9f78001b	12-LTR-mod10-R
ff8081819f838b7f019f838e9f830020	0	isbn10checkdigit	ff8081819f838b7f019f838e9f78001b	2345678910-RTL-mod11-I-X (ISBN10)
ff8081819f838b7f019f838e9f850021	0	issncheckdigit	ff8081819f838b7f019f838e9f78001b	8765432-LTR-mod11-I-X (ISSN)
ff8081819f838b7f019f838e9f870022	0	luhncheckdigit	ff8081819f838b7f019f838e9f78001b	21-RTL-mod10-I (Luhn)
ff8081819f838b7f019f838eb5bc0028	0	second_custom	ff8081819f838b7f019f838eb5bb0027	Second
ff8081819f838b7f019f838eb5bc0029	0	first	ff8081819f838b7f019f838eb5bb0027	First
\.


--
-- Data for Name: tenant_changelog; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.tenant_changelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
202012101256-001	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:08.996298	1	EXECUTED	8:daa0e8958d530b6813c18d40ba879fbd	createTable tableName=refdata_category		\N	4.19.0	\N	\N	4618588959
202012101256-002	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.001214	2	EXECUTED	8:3f049ab5ed5aa2f4e8d61c5282910f2d	createTable tableName=refdata_value		\N	4.19.0	\N	\N	4618588959
202012101256-003	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.004485	3	EXECUTED	8:d65b4c8df13007a0efdbb22252822917	addPrimaryKey constraintName=refdata_categoryPK, tableName=refdata_category		\N	4.19.0	\N	\N	4618588959
202012101256-004	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.007443	4	EXECUTED	8:4f5ab12f7af6b33b65912756f366501b	addPrimaryKey constraintName=refdata_valuePK, tableName=refdata_value		\N	4.19.0	\N	\N	4618588959
202012101256-005	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.010368	5	EXECUTED	8:f23f90e6b50aeff3f7f2bd83638102be	createIndex indexName=rdv_entry_idx, tableName=refdata_value		\N	4.19.0	\N	\N	4618588959
202012101256-006	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.01442	6	EXECUTED	8:a105c609c20752716f4207aa26086a5e	addForeignKeyConstraint baseTableName=refdata_value, constraintName=FKh4fon2a7k4y8b2sicjm0i6oy8, referencedTableName=refdata_category		\N	4.19.0	\N	\N	4618588959
202012101256-007	efreestone (manual)	setup-refdata.groovy	2026-07-21 07:23:09.018128	7	EXECUTED	8:82e64fc1d27f561d2bf6a143c898c536	addColumn tableName=refdata_category; addNotNullConstraint columnName=internal, tableName=refdata_category		\N	4.19.0	\N	\N	4618588959
202106021259-001	ianibbo (manual)	setup-refdata.groovy	2026-07-21 07:23:09.020612	8	EXECUTED	8:d68928b3abe0c46fe2657cb78a0ade24	addUniqueConstraint constraintName=RDV_UNIQUE_VALUE, tableName=refdata_value		\N	4.19.0	\N	\N	4618588959
202012101335-001	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.025201	9	EXECUTED	8:a99d14792aeb0a101133afa78d70c45c	createTable tableName=custom_property		\N	4.19.0	\N	\N	4618588959
202012101335-002	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.028454	10	EXECUTED	8:81806308e7f415917594c3c7d582fd53	createTable tableName=custom_property_blob		\N	4.19.0	\N	\N	4618588959
202012101335-003	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.031133	11	EXECUTED	8:9c839c813d04987239d9c05ba9a3884e	createTable tableName=custom_property_boolean		\N	4.19.0	\N	\N	4618588959
202012101335-004	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.033992	12	EXECUTED	8:59daab71e6018a7facf6947f88e451b6	createTable tableName=custom_property_container		\N	4.19.0	\N	\N	4618588959
202012101335-005	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.036189	13	EXECUTED	8:25775680c248e79a9bfc1105b1be8225	createTable tableName=custom_property_decimal		\N	4.19.0	\N	\N	4618588959
202012101335-006	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.038504	14	EXECUTED	8:2b26d42d05f30b36c66781cdeba5aa39	createTable tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101335-007	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.040535	15	EXECUTED	8:69fccd48bd0f5c541d4a1ea5370dd3f8	createTable tableName=custom_property_integer		\N	4.19.0	\N	\N	4618588959
202012101335-008	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.04282	16	EXECUTED	8:a2cb58fd44dc4abd86f281d811244bd2	createTable tableName=custom_property_refdata		\N	4.19.0	\N	\N	4618588959
202012101335-009	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.045167	17	EXECUTED	8:5b5fabf2eebbf5e21da85aca3eff457b	createTable tableName=custom_property_refdata_definition		\N	4.19.0	\N	\N	4618588959
202012101335-010	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.048629	18	EXECUTED	8:463d6f5467a52429d4557eb0f5d165cb	createTable tableName=custom_property_text		\N	4.19.0	\N	\N	4618588959
202012101335-011	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.051943	19	EXECUTED	8:1e4a0d01e60b17c03b68fd4411a3636f	addPrimaryKey constraintName=custom_property_blobPK, tableName=custom_property_blob		\N	4.19.0	\N	\N	4618588959
202012101335-012	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.055116	20	EXECUTED	8:f41d719cd39c4ab6e242a38600b0d719	addPrimaryKey constraintName=custom_property_booleanPK, tableName=custom_property_boolean		\N	4.19.0	\N	\N	4618588959
202012101335-013	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.057496	21	EXECUTED	8:5898a2dddf4f2d79c555cc378a5752d1	addPrimaryKey constraintName=custom_property_containerPK, tableName=custom_property_container		\N	4.19.0	\N	\N	4618588959
202012101335-014	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.06056	22	EXECUTED	8:93093461d1d94b9be5e2ab3358cffb29	addPrimaryKey constraintName=custom_property_decimalPK, tableName=custom_property_decimal		\N	4.19.0	\N	\N	4618588959
202012101335-015	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.063454	23	EXECUTED	8:a4e414c0d672608e2e929d7e30db606b	addPrimaryKey constraintName=custom_property_definitionPK, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101335-016	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.06634	24	EXECUTED	8:dee3913b5966eefa88911b0f6875279b	addPrimaryKey constraintName=custom_property_integerPK, tableName=custom_property_integer		\N	4.19.0	\N	\N	4618588959
202012101335-017	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.069051	25	EXECUTED	8:3318f5c32004fe584b4db70b334c9f69	addPrimaryKey constraintName=custom_property_refdataPK, tableName=custom_property_refdata		\N	4.19.0	\N	\N	4618588959
202012101335-018	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.072059	26	EXECUTED	8:7ed93225eb5b46825d5bb5796157030b	addPrimaryKey constraintName=custom_property_refdata_definitionPK, tableName=custom_property_refdata_definition		\N	4.19.0	\N	\N	4618588959
202012101335-019	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.075324	27	EXECUTED	8:3220d401a9968a19f0e685184581ab43	addPrimaryKey constraintName=custom_property_textPK, tableName=custom_property_text		\N	4.19.0	\N	\N	4618588959
202012101335-020	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.07795	28	EXECUTED	8:fbd46af68074ec37226f2f1262d31b3a	createIndex indexName=td_type_idx, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101335-021	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.081084	29	EXECUTED	8:f6ddbb19d4de8295300539b15cca04c4	addForeignKeyConstraint baseTableName=custom_property, constraintName=FK36grvth72fb7wu5i5xaeqjitw, referencedTableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101335-022	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.084244	30	EXECUTED	8:23bd672a92fadfd6469dfe5154262d33	addForeignKeyConstraint baseTableName=custom_property_refdata, constraintName=FK5ogn0fedwxxy4fhmq9du4qej2, referencedTableName=refdata_value		\N	4.19.0	\N	\N	4618588959
202012101335-023	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.087398	31	EXECUTED	8:9823c58ff95770cf5a817639e41f5f18	addForeignKeyConstraint baseTableName=custom_property_refdata_definition, constraintName=FKbrh88caagajlvrpaydg4tr3qx, referencedTableName=refdata_category		\N	4.19.0	\N	\N	4618588959
202012101335-024	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.08954	32	EXECUTED	8:732eb66ed6c10a9ff5a7d88639fb13de	addForeignKeyConstraint baseTableName=custom_property, constraintName=FKd5u2tgpracxvk1xw8pdreuj5h, referencedTableName=custom_property_container		\N	4.19.0	\N	\N	4618588959
202012101341-1	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.092203	33	EXECUTED	8:16c279a9c433e5709204842c0e23551d	addColumn tableName=custom_property_definition; addNotNullConstraint columnName=pd_label, tableName=custom_property_definition; addNotNullConstraint columnName=pd_weight, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-2	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.094167	34	EXECUTED	8:38c63242d7a15faf216d4371a30d64c8	addColumn tableName=custom_property_definition; addNotNullConstraint columnName=pd_primary, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-3	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.096262	35	EXECUTED	8:69ca1fa28011df21f2ebb6a852eff88d	addColumn tableName=custom_property		\N	4.19.0	\N	\N	4618588959
202012101341-4	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.099183	36	EXECUTED	8:8bde7c5bf576e92ee61d9f843d4d3e39	createIndex indexName=td_label_idx, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-5	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.101924	37	EXECUTED	8:59bced2b2cac6f74a3f2cce1e3cf7895	createIndex indexName=td_primary_idx, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-6	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.104679	38	EXECUTED	8:0f13d871c2e45dd6cb84569f08e63593	createIndex indexName=td_weight_idx, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-7	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.107767	39	EXECUTED	8:5fed195cbc1e30cf4f22b7b6db13fd4b	addColumn tableName=custom_property_definition; addNotNullConstraint columnName=default_internal, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101341-8	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.110567	40	EXECUTED	8:b2935eca1f36847ec53fb1d9a7060ba8	addColumn tableName=custom_property; addNotNullConstraint columnName=internal, tableName=custom_property		\N	4.19.0	\N	\N	4618588959
202012101341-9	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.113283	41	EXECUTED	8:948cb41d8806e490669215f531df3f54	addColumn tableName=custom_property		\N	4.19.0	\N	\N	4618588959
202012101341-10	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.117279	42	EXECUTED	8:77cef15e27ea478737a217113e0bc9c2	modifyDataType columnName=value, tableName=custom_property_integer		\N	4.19.0	\N	\N	4618588959
202012101341-11	efreestone (manual)	setup-custom-properties.groovy	2026-07-21 07:23:09.120361	43	EXECUTED	8:9055b9a76596577e630d724d0bdb7c21	modifyDataType columnName=pd_description, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
202012101426-1	efreestone (manual)	setup-app-settings.groovy	2026-07-21 07:23:09.123898	44	EXECUTED	8:6b54df370c2d421cb00ad28d83b0a028	createTable tableName=app_setting		\N	4.19.0	\N	\N	4618588959
051220201808-001	ianibbo (manual)	create-mod-service-interaction.groovy	2026-07-21 07:23:09.126773	45	EXECUTED	8:9df4ee4464a4a10dfcf2717c73a52620	createSequence sequenceName=hibernate_sequence		\N	4.19.0	\N	\N	4618588959
2021-02-01-1350-001	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.130083	46	EXECUTED	8:932db6e11b31ecfdbcea6710fc22c143	createTable tableName=external_user		\N	4.19.0	\N	\N	4618588959
2021-02-01-1350-002	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.134397	47	EXECUTED	8:909fa59dbcb693f39a94a65c7325f267	addPrimaryKey constraintName=externalUserPK, tableName=external_user		\N	4.19.0	\N	\N	4618588959
2021-02-01-1350-003	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.137764	48	EXECUTED	8:07cb9d8e48186545f5171d32a8d3e507	createTable tableName=dashboard		\N	4.19.0	\N	\N	4618588959
2021-02-01-1350-004	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.140594	49	EXECUTED	8:007575e6543d6c00e60910b61e11539a	addPrimaryKey constraintName=dashboardPK, tableName=dashboard		\N	4.19.0	\N	\N	4618588959
2021-02-01-1350-005	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.144063	50	EXECUTED	8:03754d3d8f29057d05d6cd3998175d61	addForeignKeyConstraint baseTableName=dashboard, constraintName=dashboard_owner_fk, referencedTableName=external_user		\N	4.19.0	\N	\N	4618588959
2021-02-02-1611-001	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.147682	51	EXECUTED	8:b85c6f0d025a52c4bb3060321ddf5fc7	createTable tableName=widget_type		\N	4.19.0	\N	\N	4618588959
2021-02-02-1611-002	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.150208	52	EXECUTED	8:ff7589117fbaf16c68652672ad7b3a94	addPrimaryKey constraintName=widgetTypePK, tableName=widget_type		\N	4.19.0	\N	\N	4618588959
2021-02-02-1611-003	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.153489	53	EXECUTED	8:c23a5da2f98eb5e7c82dbc96027336f5	createTable tableName=widget_definition		\N	4.19.0	\N	\N	4618588959
2021-02-02-1611-004	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.156177	54	EXECUTED	8:51cb10e02480580caf32b344b8175cd0	addPrimaryKey constraintName=widgetDefinitionPK, tableName=widget_definition		\N	4.19.0	\N	\N	4618588959
2021-02-08-1131-001	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.15954	55	EXECUTED	8:ca2daa8a06aee84662ac6465c1ed0f1e	createTable tableName=widget_instance		\N	4.19.0	\N	\N	4618588959
2021-02-08-1131-002	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.162111	56	EXECUTED	8:b4b0274a821c23591ae2c048cc56531c	addPrimaryKey constraintName=widgetInstancePK, tableName=widget_instance		\N	4.19.0	\N	\N	4618588959
2021-02-08-1131-004	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.164556	57	EXECUTED	8:57c4dd5fe52061d8d10153286fd66290	addForeignKeyConstraint baseTableName=widget_instance, constraintName=widget_instance_owner_fk, referencedTableName=dashboard		\N	4.19.0	\N	\N	4618588959
2021-03-08-1243-001	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.166623	58	EXECUTED	8:f691ebcdf3b5fca87f960a1be646005a	addColumn tableName=widget_instance		\N	4.19.0	\N	\N	4618588959
2021-04-14-1228-001	efreestone (manual)	initial-model.groovy	2026-07-21 07:23:09.170167	59	EXECUTED	8:ed8cb84c2ef802b879e0cc2894d8f913	addUniqueConstraint constraintName=widget_definition_name_version_unique, tableName=widget_definition; addUniqueConstraint constraintName=widget_type_name_version_unique, tableName=widget_type		\N	4.19.0	\N	\N	4618588959
2022-05-02-1007-001	ianibbo (manual)	number-generator-model.groovy	2026-07-21 07:23:09.176684	60	EXECUTED	8:3181b51a51b3bb5f2f4c063f7430783c	createTable tableName=number_generator; addPrimaryKey constraintName=NumberGeneratorPK, tableName=number_generator; addUniqueConstraint constraintName=NumberGeneratorUniqueCode, tableName=number_generator; createTable tableName=number_generator_se...		\N	4.19.0	\N	\N	4618588959
2022-06-15-0811-001	ianibbo (manual)	number-generator-model.groovy	2026-07-21 07:23:09.179313	61	EXECUTED	8:4b2f7219d4747182e45a32efedad8773	addColumn tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2022-06-29-0843-001	ianibbo (manual)	number-generator-model.groovy	2026-07-21 07:23:09.182164	62	EXECUTED	8:8a2de593c025f9e5318c3719ddedd093	addColumn tableName=number_generator		\N	4.19.0	\N	\N	4618588959
2022-07-21-0758-001	ianibbo (manual)	number-generator-model.groovy	2026-07-21 07:23:09.185919	63	EXECUTED	8:2b081e9741edb9b943c0d1ccb8f19a38	addColumn tableName=number_generator; addColumn tableName=number_generator_sequence; addColumn tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2022-10-13-1355-001	efreestone (manual)	number-generator-model.groovy	2026-07-21 07:23:09.188982	64	EXECUTED	8:00650364b02ea44f575842588fa48e24	addColumn tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2024-09-26-1816-001	efreestone (manual)	number-generator-model.groovy	2026-07-21 07:23:09.191323	65	EXECUTED	8:467aa5c6b0841e5699babc52da37fa9e	addColumn tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2022-08-10-1238-001	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.194775	66	EXECUTED	8:6e8df1f0435470fb283158ac632ede0a	createTable tableName=dashboard_access		\N	4.19.0	\N	\N	4618588959
2022-08-22-1638-001	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.197489	67	EXECUTED	8:d69f94eecb4d392e9c2213b9b808cafe	addNotNullConstraint columnName=da_default_user_dashboard, tableName=dashboard_access		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-001	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.200796	68	EXECUTED	8:7c8e04b3546f1f72acc23b3dee2d26ce	addForeignKeyConstraint baseTableName=dashboard_access, constraintName=dashboard_access_dashboard_FK, referencedTableName=dashboard		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-002	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.204129	69	EXECUTED	8:9888cab796f0f126c15cf5e31b166840	addForeignKeyConstraint baseTableName=dashboard_access, constraintName=dashboard_access_user_FK, referencedTableName=external_user		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-003	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.207492	70	EXECUTED	8:6074fffd144e3e64a676204b2ca5b67b	addForeignKeyConstraint baseTableName=dashboard_access, constraintName=dashboard_access_access_FK, referencedTableName=refdata_value		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-004	ethanfreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.211503	71	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-005	ethanfreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.216321	72	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-006	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.221381	73	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2022-08-11-1021-007	sosguthorpe (generated)	service-interaction-1-3.groovy	2026-07-21 07:23:09.223717	74	EXECUTED	8:37cc571bf9cd75491a96cf0cf7507a5c	dropColumn columnName=dshb_owner_fk, tableName=dashboard		\N	4.19.0	\N	\N	4618588959
2022-09-07-1553-001	efreestone (manual)	service-interaction-1-3.groovy	2026-07-21 07:23:09.226286	75	EXECUTED	8:9ae0a810f4492875e102e88838263e82	addColumn tableName=dashboard		\N	4.19.0	\N	\N	4618588959
1654077379849-21	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.231056	76	EXECUTED	8:bbe859e29dd8c9adced554405d257e8b	createTable tableName=custom_property_multi_blob; createTable tableName=custom_property_multi_blob_value; addForeignKeyConstraint baseTableName=custom_property_multi_blob_value, constraintName=FKed37wtwoq679mwy1s18bl6exr, referencedTableName=custo...		\N	4.19.0	\N	\N	4618588959
1654077379849-22	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.235263	77	EXECUTED	8:aa5322c36cfaff9e29d934df9219d143	createTable tableName=custom_property_multi_decimal; createTable tableName=custom_property_multi_decimal_value; addForeignKeyConstraint baseTableName=custom_property_multi_decimal_value, constraintName=FKi57yhini8g473uvxv8fcy9p2f, referencedTableN...		\N	4.19.0	\N	\N	4618588959
1654077379849-24	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.239579	78	EXECUTED	8:36e9017825ed3f128ba06d399acc3c39	createTable tableName=custom_property_multi_integer; createTable tableName=custom_property_multi_integer_value; addForeignKeyConstraint baseTableName=custom_property_multi_integer_value, constraintName=FK2j4jyo04f9rplaimjf9131j1m, referencedTableN...		\N	4.19.0	\N	\N	4618588959
1654077379849-26	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.243685	79	EXECUTED	8:6a38ae648cc9cf749e1d80f469abd3a8	createTable tableName=custom_property_multi_local_date; createTable tableName=custom_property_multi_local_date_value; addForeignKeyConstraint baseTableName=custom_property_multi_local_date_value, constraintName=FKlq0njvkrtu3kr3beevehf03j7, referen...		\N	4.19.0	\N	\N	4618588959
1654077379849-28	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.248018	80	EXECUTED	8:527774a17eeb62dad5068c348aa301e5	createTable tableName=custom_property_multi_refdata; createTable tableName=custom_property_multi_refdata_refdata_value; addForeignKeyConstraint baseTableName=custom_property_multi_refdata_refdata_value, constraintName=FKch1uraa9ojuygaksh67bmxxve, ...		\N	4.19.0	\N	\N	4618588959
1654077379849-30	sosguthorpe	wtk/multi-value-custprops.feat.groovy	2026-07-21 07:23:09.2545	81	EXECUTED	8:96d603b821178a3660278f3013176c47	createTable tableName=custom_property_multi_text; createTable tableName=custom_property_multi_text_value; addForeignKeyConstraint baseTableName=custom_property_multi_text_value, constraintName=FKbklek969hy5ykdxsp2nf3t5fl, referencedTableName=custo...		\N	4.19.0	\N	\N	4618588959
20220915120000-001	chas	wtk/hidden-appsetting.feat.groovy	2026-07-21 07:23:09.257787	82	EXECUTED	8:3ec5c4a5af0c7db5b0063b289f66ba57	addColumn tableName=app_setting		\N	4.19.0	\N	\N	4618588959
2023-02-16-1519-001	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.260465	83	EXECUTED	8:eaf11aee1fcae5ac7c12bd1da94bf14f	addColumn tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
2023-02-16-1519-002	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.264988	84	EXECUTED	8:b4f8197850d8324df6d7fe864e5829e1	addColumn tableName=custom_property_definition; addNotNullConstraint columnName=pd_retired, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
2023-02-16-1519-003	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.268023	85	EXECUTED	8:c575c85e251fd041672abe317c80a5bb	createIndex indexName=td_retired_idx, tableName=custom_property_definition		\N	4.19.0	\N	\N	4618588959
2023-02-16-1448-001	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.272054	86	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-02-16-1448-002	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.274957	87	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-02-16-1448-003	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.278719	88	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-02-16-1448-004	efreestone (manual)	service-interaction-2-2.groovy	2026-07-21 07:23:09.28313	89	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-08-17-1207-001	efreestone (manual)	service-interaction-3-0.groovy	2026-07-21 07:23:09.2876	90	EXECUTED	8:71ded6b3980ac34ddc6c3fba03f46674	createTable tableName=dashboard_display_data		\N	4.19.0	\N	\N	4618588959
2023-08-17-1207-002	efreestone (manual)	service-interaction-3-0.groovy	2026-07-21 07:23:09.291301	91	EXECUTED	8:8e701d2bcce76dc4f28ed398ae1c4079	addUniqueConstraint constraintName=dashboard_display_data_dash_id_unique, tableName=dashboard_display_data		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-001	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.295047	92	EXECUTED	8:8aef3e347686decfc1d9f1f89dc1f7fd	addColumn tableName=number_generator_sequence; addColumn tableName=number_generator_sequence; addColumn tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-002	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.298839	93	EXECUTED	8:7c6423bc346273a0486f815b5062631e	addForeignKeyConstraint baseTableName=number_generator_sequence, constraintName=ngs_ngs_maximum_check_FK_CONSTRAINT, referencedTableName=refdata_value		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-003	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.301767	94	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-004	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.305236	95	EXECUTED	8:01bb264dd31114111d21e071cbfc57e9	grailsChange		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-005	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.307565	96	EXECUTED	8:56f90f65a51d2cd3fa175d57597d1806	renameColumn newColumnName=ngs_check_digit_algorithm_fk, oldColumnName=ngs_check_digit_algorithm, tableName=number_generator_sequence		\N	4.19.0	\N	\N	4618588959
2023-12-08-1010-006	efreestone (manual)	service-interaction-3-1.groovy	2026-07-21 07:23:09.311238	97	EXECUTED	8:6c0f06c22b9525cde9916c33373f8e0d	addForeignKeyConstraint baseTableName=number_generator_sequence, constraintName=ngs_check_digit_algo_FK_CONSTRAINT, referencedTableName=refdata_value		\N	4.19.0	\N	\N	4618588959
2025-11-15-0903-001	ian (manual)	service-interaction-4-3.groovy	2026-07-21 07:23:09.315481	98	EXECUTED	8:675c78da42f2fa74f7e8b5df1ac1d57e	createTable tableName=db_key_pair		\N	4.19.0	\N	\N	4618588959
2026-06-22-0940-001	laemmer (manual)	number-generator-year-reset.groovy	2026-07-21 07:23:09.318727	99	EXECUTED	8:ab9587652872219f440cd0577fe05409	addColumn tableName=number_generator_sequence		4.4.0	4.19.0	\N	\N	4618588959
\.


--
-- Data for Name: tenant_changelog_lock; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.tenant_changelog_lock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: widget_definition; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.widget_definition (wdef_id, wdef_version, wdef_definition_version, wdef_name, wdef_definition, wdef_type_name, wdef_type_version) FROM stdin;
69937301-edd0-4c6c-babe-4e030232e95f	0	1.0	m4-def	{"baseUrl":"/erm/sas","results":{"columns":[{"name":"agreementName","label":"Name"}]}}	SimpleSearch	1.0
\.


--
-- Data for Name: widget_instance; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.widget_instance (wins_id, wins_version, wins_name, wins_definition_name, wins_definition_version, wins_owner_fk, wins_configuration, wins_weight) FROM stdin;
7d9b49b2-e791-4942-8938-8248d2630120	0	M4 widget one	m4-def	1.0	38668b57-5a37-44f8-adec-5594f02067a0	{"filters":[]}	0
4b63805e-f211-4aa6-8109-3c4ac21a7f12	0	M4 widget two	m4-def	1.0	38668b57-5a37-44f8-adec-5594f02067a0	{"filters":[{"name":"x"}]}	1
\.


--
-- Data for Name: widget_type; Type: TABLE DATA; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

COPY r13b_mod_service_interaction.widget_type (wtype_id, wtype_version, wtype_type_version, wtype_name, wtype_schema) FROM stdin;
fa1d4b15-f2bb-416b-bdd1-cb07ffec73b5	0	1.0	SimpleSearch	{"$schema":"http://json-schema.org/draft-07/schema#","title":"SimpleSearch WidgetDefinition Schema","type":"object","description":"SimpleSearch widget type","additionalProperties":false,"required":["baseUrl","results"],"properties":{"baseUrl":{"type":"string","description":"The base url queries built with this widget will go to"},"resource":{"type":"string","description":"the resource that this SimpleSearch definition is fetching. Used by the Registry"},"results":{"$ref":"#/$defs/results"},"matches":{"$ref":"#/$defs/matches"},"filters":{"$ref":"#/$defs/filters"},"sort":{"$ref":"#/$defs/sort"},"configurableProperties":{"$ref":"#/$defs/configurableProperties"}},"$defs":{"results":{"type":"object","title":"Results","description":"Contains all the information the dashboard needs to fetch and parse results","additionalProperties":false,"required":["columns"],"properties":{"columns":{"type":"array","items":{"$ref":"#/$defs/resultColumn"}}}},"resultColumn":{"type":"object","title":"Result column","description":"Describes the columns to be made available in the output","additionalProperties":false,"required":["name"],"properties":{"accessPath":{"type":"string","description":"a string defining the path to the specified object property. Can be absent in the case of a 'resultColumn' being defined by the Registry entry for a resource."},"label":{"type":"string","description":"an optional string prescribing the display label of the field"},"name":{"type":"string","description":"a string defining the name of the property for this column"},"valueType":{"type":"string","enum":["String","Integer","Float","Boolean","Date","DateTime","Link","Array"],"description":"a string defining the type of property we are displaying. Not required if using registry to display column"},"arrayDisplayPath":{"type":"string","description":"a string defining the path to the property within the array object to display. If left blank then the entire array will attempt to display."}},"allOf":[{"not":{"properties":{"valueType":{"not":{"const":"Array"}}},"required":["arrayDisplayPath"]}}]},"matches":{"type":"object","title":"Matches","description":"Contains all the information the dashboard needs to configure 'match' type queries","additionalProperties":false,"required":["columns","termConfigurable"],"properties":{"columns":{"type":"array","items":{"$ref":"#/$defs/matchColumn"}},"defaultTerm":{"type":"string","description":"A string housing the default term used for match queries for a definition"},"termConfigurable":{"type":"boolean","description":"A boolean value which determines if the match term is user configurable or not."}},"allOf":[{"anyOf":[{"properties":{"termConfigurable":{"const":false}},"required":["defaultTerm"]},{"properties":{"termConfigurable":{"not":{"const":false}}}}]}]},"matchColumn":{"type":"object","title":"Match column","description":"Describes the columns to be made available for match searching","additionalProperties":false,"required":["accessPath","default","name"],"properties":{"accessPath":{"type":"string","description":"a string defining the path to the specified object property."},"default":{"type":"boolean","description":"A boolean value used to check whether or not this match should be set by default"},"label":{"type":"string","description":"an optional string prescribing the display label of the field"},"name":{"type":"string","description":"a string defining the name of the property for this column"}},"allOf":[{"not":{"properties":{"valueType":{"not":{"const":"Array"}}},"required":["arrayDisplayPath"]}}]},"filters":{"type":"object","title":"Filters","description":"Contains all the information the dashboard needs to perform filtering of results","additionalProperties":false,"required":["columns"],"properties":{"columns":{"type":"array","items":{"$ref":"#/$defs/filterColumn"}}}},"filterColumn":{"type":"object","title":"Filter column","description":"Describes the columns the output is able to filter on","additionalProperties":false,"required":["filterPath","name","valueType"],"properties":{"filterPath":{"type":"string","description":"a string defining the path on which we must filter for this property"},"label":{"type":"string","description":"an optional string prescribing the display label of the field"},"name":{"type":"string","description":"a string defining the name of the property for this column"},"valueType":{"type":"string","enum":["String","Integer","Float","Boolean","Date","Enum","UUID","Array"],"description":"a string defining the type of property we are filtering on"},"enumValues":{"type":"array","items":{"$ref":"#/$defs/enumValues"},"description":"A collection of options for the value, where valueType is 'Enum'"},"comparators":{"type":"array","item":{"type":"string","description":"a string containing a comparator for this filter value, eg '>' or '=='"},"description":"An array of comparators valid for this filter"},"resource":{"type":"string","description":"A string defining the resource type this filterField belongs to. Used by the Registry."}},"allOf":[{"anyOf":[{"properties":{"valueType":{"not":{"const":"Enum"}}},"not":{"required":["enumValues"]}},{"properties":{"valueType":{"const":"Enum"}},"required":["enumValues"]}]},{"anyOf":[{"properties":{"valueType":{"not":{"const":"Boolean"}}},"required":["comparators"]},{"properties":{"valueType":{"const":"Boolean"}}}]},{"not":{"properties":{"valueType":{"not":{"const":"UUID"}}},"required":["resource"]}}]},"enumValues":{"type":"object","title":"Enum Values","description":"One of the enum values for the field","additionalProperties":false,"required":["value"],"properties":{"value":{"type":"string","description":"A value for this enum"},"label":{"type":"string","description":"An optional label to replace the value of the enum"}}},"sort":{"type":"object","title":"Sort","description":"Contains all the information the dashboard needs to perform sorting of results","additionalProperties":false,"required":["columns"],"properties":{"columns":{"type":"array","items":{"$ref":"#/$defs/sortColumn"}}}},"sortColumn":{"type":"object","title":"Sort column","description":"Describes the columns the output is able to sort on","additionalProperties":false,"required":["sortPath","name","sortTypes"],"properties":{"sortPath":{"type":"string","description":"a string defining the path on which we must sort for this property"},"label":{"type":"string","description":"an optional string prescribing the display label of the field"},"name":{"type":"string","description":"a string defining the name of the property for this column"},"sortTypes":{"type":"array","items":{"type":"string","enum":["asc","desc"]}}}},"configurableProperties":{"type":"object","title":"Other properties","description":"A collection of other properties which can be configured/made configurable","additionalProperties":false,"properties":{"urlLink":{"$ref":"#/$defs/urlLink"},"numberOfRows":{"$ref":"#/$defs/numberOfRows"}}},"urlLink":{"type":"object","title":"URL link","description":"An external link to be accessed at the bottom of the widget","requiredProperties":["configurable"],"properties":{"configurable":{"$ref":"#/$defs/configurable"},"defValue":{"type":"string","description":"an optional string containing a default link"}}},"numberOfRows":{"type":"object","title":"Number of rows","description":"Define the max amount of entries to return from the endpoint","requiredProperties":["configurable"],"properties":{"configurable":{"$ref":"#/$defs/configurable"},"defValue":{"type":"number","description":"an optional string containing a default number of rows"}},"anyOf":[{"not":{"properties":{"configurable":{"const":false}},"required":["configurable"]}},{"required":["defValue"]}]},"configurable":{"type":"boolean","description":"A true/false value which determines whether the user can configure beyond the default or not"}}}
\.


--
-- Name: custom_property_id_seq; Type: SEQUENCE SET; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

SELECT pg_catalog.setval('r13b_mod_service_interaction.custom_property_id_seq', 1, false);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

SELECT pg_catalog.setval('r13b_mod_service_interaction.hibernate_sequence', 1, false);


--
-- Name: number_generator NumberGeneratorPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator
    ADD CONSTRAINT "NumberGeneratorPK" PRIMARY KEY (ng_id);


--
-- Name: number_generator_sequence NumberGeneratorSequencePK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator_sequence
    ADD CONSTRAINT "NumberGeneratorSequencePK" PRIMARY KEY (ngs_id);


--
-- Name: number_generator_sequence NumberGeneratorSequenceUniqueCode; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator_sequence
    ADD CONSTRAINT "NumberGeneratorSequenceUniqueCode" UNIQUE (ngs_owner, ngs_code);


--
-- Name: number_generator NumberGeneratorUniqueCode; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator
    ADD CONSTRAINT "NumberGeneratorUniqueCode" UNIQUE (ng_code);


--
-- Name: custom_property custom_propertyPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property
    ADD CONSTRAINT "custom_propertyPK" PRIMARY KEY (id);


--
-- Name: custom_property_blob custom_property_blobPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_blob
    ADD CONSTRAINT "custom_property_blobPK" PRIMARY KEY (id);


--
-- Name: custom_property_boolean custom_property_booleanPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_boolean
    ADD CONSTRAINT "custom_property_booleanPK" PRIMARY KEY (id);


--
-- Name: custom_property_container custom_property_containerPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_container
    ADD CONSTRAINT "custom_property_containerPK" PRIMARY KEY (id);


--
-- Name: custom_property_decimal custom_property_decimalPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_decimal
    ADD CONSTRAINT "custom_property_decimalPK" PRIMARY KEY (id);


--
-- Name: custom_property_definition custom_property_definitionPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_definition
    ADD CONSTRAINT "custom_property_definitionPK" PRIMARY KEY (pd_id);


--
-- Name: custom_property_integer custom_property_integerPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_integer
    ADD CONSTRAINT "custom_property_integerPK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_blob custom_property_multi_blobPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_blob
    ADD CONSTRAINT "custom_property_multi_blobPK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_decimal custom_property_multi_decimalPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_decimal
    ADD CONSTRAINT "custom_property_multi_decimalPK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_integer custom_property_multi_integerPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_integer
    ADD CONSTRAINT "custom_property_multi_integerPK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_local_date custom_property_multi_local_datePK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_local_date
    ADD CONSTRAINT "custom_property_multi_local_datePK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_refdata custom_property_multi_refdataPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_refdata
    ADD CONSTRAINT "custom_property_multi_refdataPK" PRIMARY KEY (id);


--
-- Name: custom_property_multi_text custom_property_multi_textPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_text
    ADD CONSTRAINT "custom_property_multi_textPK" PRIMARY KEY (id);


--
-- Name: custom_property_refdata custom_property_refdataPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_refdata
    ADD CONSTRAINT "custom_property_refdataPK" PRIMARY KEY (id);


--
-- Name: custom_property_refdata_definition custom_property_refdata_definitionPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_refdata_definition
    ADD CONSTRAINT "custom_property_refdata_definitionPK" PRIMARY KEY (pd_id);


--
-- Name: custom_property_text custom_property_textPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_text
    ADD CONSTRAINT "custom_property_textPK" PRIMARY KEY (id);


--
-- Name: dashboard dashboardPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.dashboard
    ADD CONSTRAINT "dashboardPK" PRIMARY KEY (dshb_id);


--
-- Name: dashboard_display_data dashboard_display_data_dash_id_unique; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.dashboard_display_data
    ADD CONSTRAINT dashboard_display_data_dash_id_unique UNIQUE (ddd_dash_id);


--
-- Name: external_user externalUserPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.external_user
    ADD CONSTRAINT "externalUserPK" PRIMARY KEY (eu_id);


--
-- Name: refdata_value rdv_unique_value; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.refdata_value
    ADD CONSTRAINT rdv_unique_value UNIQUE (rdv_owner, rdv_value);


--
-- Name: refdata_category refdata_categoryPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.refdata_category
    ADD CONSTRAINT "refdata_categoryPK" PRIMARY KEY (rdc_id);


--
-- Name: refdata_value refdata_valuePK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.refdata_value
    ADD CONSTRAINT "refdata_valuePK" PRIMARY KEY (rdv_id);


--
-- Name: tenant_changelog_lock tenant_changelog_lock_pkey; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.tenant_changelog_lock
    ADD CONSTRAINT tenant_changelog_lock_pkey PRIMARY KEY (id);


--
-- Name: widget_definition widgetDefinitionPK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_definition
    ADD CONSTRAINT "widgetDefinitionPK" PRIMARY KEY (wdef_id);


--
-- Name: widget_instance widgetInstancePK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_instance
    ADD CONSTRAINT "widgetInstancePK" PRIMARY KEY (wins_id);


--
-- Name: widget_type widgetTypePK; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_type
    ADD CONSTRAINT "widgetTypePK" PRIMARY KEY (wtype_id);


--
-- Name: widget_definition widget_definition_name_version_unique; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_definition
    ADD CONSTRAINT widget_definition_name_version_unique UNIQUE (wdef_name, wdef_definition_version);


--
-- Name: widget_type widget_type_name_version_unique; Type: CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_type
    ADD CONSTRAINT widget_type_name_version_unique UNIQUE (wtype_name, wtype_type_version);


--
-- Name: rdv_entry_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX rdv_entry_idx ON r13b_mod_service_interaction.refdata_value USING btree (rdv_value, rdv_owner);


--
-- Name: td_label_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX td_label_idx ON r13b_mod_service_interaction.custom_property_definition USING btree (pd_label);


--
-- Name: td_primary_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX td_primary_idx ON r13b_mod_service_interaction.custom_property_definition USING btree (pd_primary);


--
-- Name: td_retired_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX td_retired_idx ON r13b_mod_service_interaction.custom_property_definition USING btree (pd_retired);


--
-- Name: td_type_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX td_type_idx ON r13b_mod_service_interaction.custom_property_definition USING btree (pd_type);


--
-- Name: td_weight_idx; Type: INDEX; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

CREATE INDEX td_weight_idx ON r13b_mod_service_interaction.custom_property_definition USING btree (pd_weight);


--
-- Name: custom_property_multi_integer_value FK2j4jyo04f9rplaimjf9131j1m; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_integer_value
    ADD CONSTRAINT "FK2j4jyo04f9rplaimjf9131j1m" FOREIGN KEY (custom_property_multi_integer_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_integer(id);


--
-- Name: custom_property FK36grvth72fb7wu5i5xaeqjitw; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property
    ADD CONSTRAINT "FK36grvth72fb7wu5i5xaeqjitw" FOREIGN KEY (definition_id) REFERENCES r13b_mod_service_interaction.custom_property_definition(pd_id);


--
-- Name: custom_property_refdata FK5ogn0fedwxxy4fhmq9du4qej2; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_refdata
    ADD CONSTRAINT "FK5ogn0fedwxxy4fhmq9du4qej2" FOREIGN KEY (value_id) REFERENCES r13b_mod_service_interaction.refdata_value(rdv_id);


--
-- Name: custom_property_multi_text_value FKbklek969hy5ykdxsp2nf3t5fl; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_text_value
    ADD CONSTRAINT "FKbklek969hy5ykdxsp2nf3t5fl" FOREIGN KEY (custom_property_multi_text_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_text(id);


--
-- Name: custom_property_refdata_definition FKbrh88caagajlvrpaydg4tr3qx; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_refdata_definition
    ADD CONSTRAINT "FKbrh88caagajlvrpaydg4tr3qx" FOREIGN KEY (category_id) REFERENCES r13b_mod_service_interaction.refdata_category(rdc_id);


--
-- Name: custom_property_multi_refdata_refdata_value FKch1uraa9ojuygaksh67bmxxve; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_refdata_refdata_value
    ADD CONSTRAINT "FKch1uraa9ojuygaksh67bmxxve" FOREIGN KEY (custom_property_multi_refdata_value_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_refdata(id);


--
-- Name: custom_property FKd5u2tgpracxvk1xw8pdreuj5h; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property
    ADD CONSTRAINT "FKd5u2tgpracxvk1xw8pdreuj5h" FOREIGN KEY (parent_id) REFERENCES r13b_mod_service_interaction.custom_property_container(id);


--
-- Name: custom_property_multi_blob_value FKed37wtwoq679mwy1s18bl6exr; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_blob_value
    ADD CONSTRAINT "FKed37wtwoq679mwy1s18bl6exr" FOREIGN KEY (custom_property_multi_blob_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_blob(id);


--
-- Name: refdata_value FKh4fon2a7k4y8b2sicjm0i6oy8; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.refdata_value
    ADD CONSTRAINT "FKh4fon2a7k4y8b2sicjm0i6oy8" FOREIGN KEY (rdv_owner) REFERENCES r13b_mod_service_interaction.refdata_category(rdc_id);


--
-- Name: custom_property_multi_decimal_value FKi57yhini8g473uvxv8fcy9p2f; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_decimal_value
    ADD CONSTRAINT "FKi57yhini8g473uvxv8fcy9p2f" FOREIGN KEY (custom_property_multi_decimal_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_decimal(id);


--
-- Name: custom_property_multi_refdata_refdata_value FKjqol9rr523a3gl1cfi9p3sdu5; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_refdata_refdata_value
    ADD CONSTRAINT "FKjqol9rr523a3gl1cfi9p3sdu5" FOREIGN KEY (refdata_value_id) REFERENCES r13b_mod_service_interaction.refdata_value(rdv_id);


--
-- Name: custom_property_multi_local_date_value FKlq0njvkrtu3kr3beevehf03j7; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.custom_property_multi_local_date_value
    ADD CONSTRAINT "FKlq0njvkrtu3kr3beevehf03j7" FOREIGN KEY (custom_property_multi_local_date_id) REFERENCES r13b_mod_service_interaction.custom_property_multi_local_date(id);


--
-- Name: dashboard_access dashboard_access_access_FK; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.dashboard_access
    ADD CONSTRAINT "dashboard_access_access_FK" FOREIGN KEY (da_access_fk) REFERENCES r13b_mod_service_interaction.refdata_value(rdv_id);


--
-- Name: dashboard_access dashboard_access_dashboard_FK; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.dashboard_access
    ADD CONSTRAINT "dashboard_access_dashboard_FK" FOREIGN KEY (da_dashboard_fk) REFERENCES r13b_mod_service_interaction.dashboard(dshb_id);


--
-- Name: dashboard_access dashboard_access_user_FK; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.dashboard_access
    ADD CONSTRAINT "dashboard_access_user_FK" FOREIGN KEY (da_user_fk) REFERENCES r13b_mod_service_interaction.external_user(eu_id);


--
-- Name: number_generator_sequence ngs_check_digit_algo_FK_CONSTRAINT; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator_sequence
    ADD CONSTRAINT "ngs_check_digit_algo_FK_CONSTRAINT" FOREIGN KEY (ngs_check_digit_algorithm_fk) REFERENCES r13b_mod_service_interaction.refdata_value(rdv_id);


--
-- Name: number_generator_sequence ngs_ngs_maximum_check_FK_CONSTRAINT; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator_sequence
    ADD CONSTRAINT "ngs_ngs_maximum_check_FK_CONSTRAINT" FOREIGN KEY (ngs_maximum_check_fk) REFERENCES r13b_mod_service_interaction.refdata_value(rdv_id);


--
-- Name: number_generator_sequence number_generator_sequence_owner_fk; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.number_generator_sequence
    ADD CONSTRAINT number_generator_sequence_owner_fk FOREIGN KEY (ngs_owner) REFERENCES r13b_mod_service_interaction.number_generator(ng_id);


--
-- Name: widget_instance widget_instance_owner_fk; Type: FK CONSTRAINT; Schema: r13b_mod_service_interaction; Owner: folio_admin
--

ALTER TABLE ONLY r13b_mod_service_interaction.widget_instance
    ADD CONSTRAINT widget_instance_owner_fk FOREIGN KEY (wins_owner_fk) REFERENCES r13b_mod_service_interaction.dashboard(dshb_id);


--
-- PostgreSQL database dump complete
--

\unrestrict UaHySknud9bVhBiH9CLC9vPtPEQ5BW2CmYYicPC2ikQvhIJndnddh0VOje0jK4a

